### ISSUE TITLE
Enumerating in solution environment

### ISSUE THREAD

**Issue by purevbadral** [Jinwen-XU/homework#2]
Hello, I tried to include enumerating a list in solution environment in my document.

```
\begin{soluenumerate}
    \item 1
    \item 2
    \item 3
\end{soluenumerate}

```

But I got this error:
Undefined control sequence.
<argument> \l__minimalist_item_indentation_dim 

the same goes with \begin{enumerate}...\end{enumerate}.

Help me plees :3
<img width="605" alt="Screenshot 2023-10-18 at 7 05 49 AM" src="https://github.com/Jinwen-XU/homework/assets/130972138/0244c643-4965-4cad-b72e-e94ca590a635">

**Comment by Jinwen-XU** [comment]
Since you are trying to use `soluenumerate` I believe that you have already looked into the code in `homework.sty`? Thank you for this enthusiasm :)

In fact `soluenumerate` serves as an internal environment, and in the `solution` environment the `enumerate` environment has been redefined to be  `soluenumerate`. I hope that I haven't included any instance of `soluenumerate` in the demo documents. If it is in one of the demo/example document that you saw this `soluenumerate`, please kindly tell me, this should definitely be corrected.

Regarding you question, I think it might be due to that you are not using the newest version of the package `minimalist`, which provides the base document class for `homework`. Please try to update your TeX distribution, after that, if the problem still present, I shall take a further look into it (for now it works fine on my side).

<img width="802" alt="image" src="https://github.com/Jinwen-XU/homework/assets/80377812/16025d04-81ca-4bc5-8567-c669124ec7d2">

**Comment by Jinwen-XU** [comment]
By the way, it seems like you are from Korea? If not I apologize for my misunderstanding. But If so, perhaps I owe you a little "sorry", since this package currently doesn't support Korean. Adding support of a new language requires a lot of work and confirmation, and I shall probably still have to wait at least six or more months before I can meet my only friend who speaks Korean...but this is definitely on the schedule... :)

**Comment by purevbadral** [comment]
Ahhh now it works, it was just `minimalist` package issue. Thank you for extra explanation which I def needed❤️.

Yes, I was digging just the whole `homework.cls` to identify what was going wrong😭. Now it works perfectly fine!. And don't worry, you didn't include any instance of `soluenumerate` in any documents except in the `.cls` file.

Oh, my university teaches almost all the classes in english, and thus I really don't need the Korean version. But If you include it it'd be handy for others. It is indeed such an exquisite and helpful class. Thank you for saving my time and this should be one the reason why I should thank u!!! I definitely support this project!!!
